# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    campaignchain.location.linkedin.user:
        bundle_name: "campaignchain/location-linkedin"
        module_identifier: "campaignchain-linkedin-user"

services:
#    campaignchain_location_linked_in.example:
#        class: %campaignchain_location_linked_in.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
