# This file is part of the CampaignChain package.
#
# (c) Sandro Groganz <sandro@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
#    campaignchain_location_linked_in.example.class: CampaignChain\Location\LinkedInBundle\Example

services:
#    campaignchain_location_linked_in.example:
#        class: %campaignchain_location_linked_in.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
